### ISSUE TITLE
/meter stores a wrong timestamp if not set in the payload message

### ISSUE THREAD

**Issue by AitorF** [DITAS-Project/VDC-Logging-Agent#13]
A `POST` to `/meter` with the following payload (note `timestamp` is not passed)

![image](https://user-images.githubusercontent.com/2410661/52268560-23fbec80-293c-11e9-90c1-187257017004.png)

results in this entry with a wrong timestamp:

![image](https://user-images.githubusercontent.com/2410661/52268549-1f373880-293c-11e9-94ca-f128404f1139.png)

**Comment by tawalaya** [comment]
See #10 and #11 the timestamp in both log and meter are deprecated.
